### ISSUE TITLE
Missing files in new schema

### ISSUE THREAD

**Issue by jasonheffner** [instructure/canvas-data-cli#11]
The grading_period_fact, grading_period_dim, grading_period_group_dim tables are missing when run, but the new score tables are included. These were tables in the new schema version 1.16.0 but don't seem to be downloading. I'm not sure if this is a problem with the script or the API. Only 79 tables are listed when downloading. Do I need to re-generate my api key?

**Comment by SecurityInsanity** [comment]
Hey @jasonheffner ,

Sorry for the late reply to this, are you still running into this? Generally we publish release notes the night before a dump is released. So you could have not hit a dump with those tables yet. (Since Scores were actually published before grading_periods).

If so can you reply with your canvas url? (You can also email: canvasdatahelp@instructure.com and we'll pick it up too).

Thanks

**Comment by jasonheffner** [comment]
Yes, I'm still seeing empty tables locally, and within Unizin. Are these tables not populated?

**Comment by SecurityInsanity** [comment]
Hey @jasonheffner ,

So looking at unizin, it appears they don't have any grading periods within canvas, and as such aren't populated. I assume the same will be for your school (though I don't know who you're with so can't check). I've also double checked my personal sandbox which does have grading periods, and the data is exported.

So I'm guessing if you aren't seeing any it's because they aren't in Canvas.

**Comment by jasonheffner** [comment]
That makes sense. I wanted to make sure it wasn't a problem with the tool. I'm at PSU.

**Comment by SecurityInsanity** [comment]
Yep PSU doesn't seem to have any grading periods within Canvas either. So it would make sense those aren't populated. :+1: I'm going to go ahead, and close this issue.

Feel free to re-open if I missed something.
